# Custom Language File for Launcher Customizer

[ejs.app]
title = "Bloczki Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/kuqis/BloczkiLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/3TKUw3DVA4"

[ejs.settings]
sourceGithubLink = "https://github.com/kuqis/BloczkiLauncher"
supportLink = "https://github.com/kuqis/BloczkiLauncher/issues"

[ejs.welcome]
welcomeHeader = "Witaj w oficjalnym launcherze serwera bloczki.fun!"
welcomeDescription = "Dołącz do zmodowanego serwera Minecraft Bloczki.fun i odkryj zupełnie nowy wymiar rozgrywki! Z pełną gamą unikalnych modów, wyjątkowych funkcji i aktywną społecznością, czeka na Ciebie mnóstwo emocjonujących przygód. Buduj, walcz, twórz i rozwijaj się w świecie, który nie ma sobie równych! Nie czekaj – zabawa i niezapomniane chwile czekają na Ciebie na Bloczki.fun!"
welcomeDescCTA = "Dołącz do bloczki.fun"
