[ejs.landing]
updateAvailableTooltip = "Dostępna aktualizacja"
usernamePlaceholder = "Nick"
usernameEditButton = "Edytuj"
settingsTooltip = "Ustawienia"
serverStatus = "SERWER"
serverStatusPlaceholder = "OFFLINE"
launchButton = "GRAJ"
launchButtonPlaceholder = "&#8226; Wybierz serwer"
launchDetails = "Proszę czekać.."

[ejs.login]
loginCancelText = "Anuluj"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Nieprawidłowy adres e-mail"
loginEmailPlaceholder = "E-MAIL LUB NAZWA UŻYTKOWNIKA"
loginPasswordError = "* Obowiązkowy"
loginPasswordPlaceholder = "HASŁO"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Zapomniałeś hasła?"
loginRememberMeText = "Zapamiętać logowanie?"
loginButtonText = "LOGIN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Potrzebujesz konta?"
loginPasswordDisclaimer1 = "Twoje hasło zostanie wysłane bezpośrednio do Mojang."
loginPasswordDisclaimer2 = "{appName} is not affiliated with Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opcje logowania"
loginWithMicrosoft = "Zaloguj się za pomocą Microsoft"
loginWithMojang = "Zaloguj się za pomocą Mojang"
cancelButton = "Anuluj"

[ejs.overlay]
serverSelectHeader = "Dostępne serwery"
serverSelectConfirm = "Wybierz"
serverSelectCancel = "Anuluj"
accountSelectHeader = "Wybierz konto"
accountSelectConfirm = "Wybierz"
accountSelectCancel = "Anuluj"

[ejs.settings]
navHeaderText = "Ustawienia"
navAccount = "Konta"
navMinecraft = "Minecraft"
navMods = "Mody"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Na"
navUpdates = "Aktualizacje"
navDone = "Zapisz i zamknij"
tabAccountHeaderText = "Ustawienia konta"
tabAccountHeaderDesc = "Dodaj nowe konta lub skonfiguruj istniejące."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Dodaj konto Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Dodaj konto Mojang"
addCrackedAccount = "+ Dodaj konto Offline"
minecraftTabHeaderText = "Ustawienia gry"
minecraftTabHeaderDesc = "Opcje związane z grą."
gameResolutionTitle = "Rozdzielczość"
launchFullscreenTitle = "Otwórz na pełnym ekranie."
autoConnectTitle = "Automatycznie połącz z serwerem."
launchDetachedTitle = "Proces gry niezależny od launchera."
launchDetachedDesc = "Jeśli opcja nie jest zaznaczona, gra zostanie zamknięta po zamknięciu launchera."
tabModsHeaderText = "Mody"
tabModsHeaderDesc = "Wyłącz lub włącz mody."
switchServerButton = "Do wymiany"
requiredMods = "Wymagane mody"
optionalMods = "Opcjonalne mody"
dropinMods = "Wrzucone mody"
addMods = "Dodaj mody"
dropinRefreshNote = "(F5, aby zaktualizować)"
shaderpacks = "Shadery"
shaderpackDesc = "Włącz lub wyłącz shadery."
selectShaderpack = "Wybierz shadery"
tabJavaHeaderText = "Ustawienia Javy"
tabJavaHeaderDesc = "Skonfiguruj swoją Javę (zaawansowane)."
memoryTitle = "Pamięć"
maxRAM = "Maksymalna ilość pamięci RAM"
minRAM = "Minimalna ilość pamięci RAM"
memoryDesc = "Zalecane minimum to 3 gigabajty. Pozostawienie tej samej wartości minimalnej i maksymalnej może zmniejszyć opóźnienie."
memoryTotalTitle = "Całkowicie"
memoryAvailableTitle = "Dostępne"
javaExecutableTitle = "Execute java"
javaExecSelDialogTitle = "Wybierz plik wykonywalny Java"
javaExecSelButtonText = "Wybierz Plik"
javaExecDesc = "Plik wykonywalny jest sprawdzany po uruchomieniu gry."
javaPathDesc = "Ścieżka musi kończyć się ciągiem <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Dodatkowe opcje JVM"
jvmOptsDesc = "Dodatkowe opcje, które będą działać z grą. <em>-Xms</em> i <em>-Xmx</em> nie mogą zostać uwzględnione."
launcherTabHeaderText = "Opcje programu uruchamiającego"
launcherTabHeaderDesc = "Opcje związane z Launcherem."
allowPrereleaseTitle = "Zezwalaj na aktualizacje przed wydaniem."
allowPrereleaseDesc = "Wersje wstępne zawierają nowe, nieprzetestowane funkcje.<br>To pole będzie zawsze włączone, jeśli używasz wersji wstępnej."
dataDirectoryTitle = "wybierz Katalog"
selectDataDirectory = "Wybierz folder"
chooseFolder = "Wybierz folder"
dataDirectoryDesc = "Wszystkie pliki gier i pliki Java będą znajdować się w tym folderze."
aboutTabHeaderText = "About"
aboutTabHeaderDesc = "View information and release notes for the current version."
aboutTitle = "{appName}"
stableRelease = "Stable Release"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Pomoc"
devToolsConsole = "DevTools Console"
releaseNotes = "Release Notes"
changelog = "Changelog"
noReleaseNotes = "No Release Notes"
viewReleaseNotes = "View Release Notes on GitHub"
launcherUpdatesHeaderText = "Launcher Updates"
launcherUpdatesHeaderDesc = "Pobierz i zainstaluj aktualizacje z naszego Launchera."
checkForUpdates = "Sprawdź aktualizacje"
whatsNew = "Co nowego?"
updateReleaseNotes = "Update Release Notes"

[ejs.waiting]
waitingText = "Czekam na odpowiedź Microsoftu.."

[ejs.welcome]
continueButton = "Kontynuuj"


[js.discord]
waiting = "Czekam na Discorda.."
state = "Serwer: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft Login"
microsoftLogoutTitle = "Microsoft Logout"

[js.login]
login = "ZALOGUJ"
loggingIn = "ŁĄCZENIE"
success = "GOTOWE"
tryAgain = "Spróbuj ponownie"

[js.login.error]
invalidValue = "* Nieprawidłowa hasło lub e-mail"
requiredValue = "* Wymagane"

[js.login.error.unknown]
title = "Wystąpił nieznany błąd"
desc = "Wystąpił nieznany błąd. Skontaktuj się z pomocą techniczną poprzez Discord."

[js.landing.launch]
pleaseWait = "Proszę czekać.."
failureTitle = "Wystąpił błąd podczas wykonywania"
failureText = "Skontaktuj się z pomocą techniczną poprzez discord."
okay = "Okej"

[js.landing.selectedAccount]
noAccountSelected = "Nie wybrano konta"

[js.landing.selectedServer]
noSelection = "Nie wybrano żadnego serwera"
loading = "Ładowanie.."

[js.landing.serverStatus]
server = "SERWER"
offline = "OFFLINE"
players = "GRACZY"

[js.landing.systemScan]
checking = "Sprawdzanie systemu.."
noCompatibleJava = "Instalacja Java<br>nie jest kompatybilna"
installJavaMessage = "Aby grać w Minecraft, potrzebujesz 64-bitowej instalacji Java. Czy chcesz zainstalować?"
installJava = "Zainstaluj Javę"
installJavaManually = "Zainstaluj ręcznie"
javaDownloadPrepare = "Przygotowanie do pobrania Java.."
javaDownloadFailureTitle = "Wystąpił błąd podczas próby pobrania oprogramowania Java"
javaDownloadFailureText = "Skontaktuj się z nami na discord."
javaRequired = "Java jest obowiązkowa<br>do gry"
javaRequiredMessage = 'Potrzebujesz 64-bitowej instalacji Java.<br><br>Możesz zainstalować ją ręcznie.'
javaRequiredDismiss = "Rozumiem"
javaRequiredCancel = "Wróć"

[js.landing.downloadJava]
findJdkFailure = "Błąd podczas próby znalezienia wersji pakietu Java JDK."
javaDownloadCorruptedError = "Plik uszkodzony. Spróbuj ponownie."
extractingJava = "Rozpakowywanie Javy"
javaInstalled = "Zainstalowano Javę!"

[js.landing.dlAsync]
loadingServerInfo = "Ładowanie informacji.."
fatalError = "Fatalny błąd"
unableToLoadDistributionIndex = "Nie można załadować informacji o serwerze."
pleaseWait = "Proszę czekać.."
errorDuringLaunchTitle = "Podczas uruchamiania wystąpił błąd"
seeConsoleForDetails = "Skontaktuj się z pomocą techniczną na discordzie pod adresem https://discord.gg/GWZVx9PJ"
validatingFileIntegrity = "Sprawdzanie spójności plików."
errorDuringFileVerificationTitle = "Wystąpił błąd weryfikacji"
downloadingFiles = "Pobieranie plików.."
errorDuringFileDownloadTitle = "Podczas pobierania wystąpił błąd"
preparingToLaunch = "Przygotowanie do uruchomienia..."
launchingGame = "Rozpoczynanie gry.."
launchWrapperNotDownloaded = "Wystąpił nieznany błąd. Skontaktuj się z pomocą techniczną na Discordzie."
doneEnjoyServer = "Gotowy. Miłej zabawy!"
checkConsoleForDetails = "Sprawdź konsolę, aby uzyskać więcej szczegółów lub skontaktuj się z nami przez discord."

[js.landing.news]
checking = "Checking for News"

[js.landing.discord]
loading = "Otwieranie gry.."
joining = "Wchodzisz na serwer bloczki.fun!"
joined = "Miłego zwiedzania!"

[js.overlay]
dismiss = "Odrzuć"

[js.settings.fileSelectors]
executables = "Pliki wykonywalne"
allFiles = "Wszystkie pliki"

[js.settings.mstfLogin]
errorTitle = "Coś poszło nie tak"
errorMessage = "Uwierzytelnienie Microsoft nie powiodło się. Spróbuj ponownie."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Coś poszło nie tak"
errorMessage = "Wystąpił błąd podczas wylogowywania. Spróbuj ponownie."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Wybierz Konto"
selectedButton = "Wybrane konto &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Ostrzeżenie<br>To jest Twoje ostatnie konto"
lastAccountWarningMessage = "Aby korzystać z Launchera musisz być zalogowany. <br><br>Czy na pewno chcesz się wylogować?"
confirmButton = "Jestem pewien"
cancelButton = "Anuluj"

[js.settings.authAccountPopulate]
username = "Użytkownik"
uuid = "UUID"
selectAccount = "Wybierz konto"
selectedAccount = "Wybrane konto ✓"
logout = "Wyloguj się"

[js.settings.dropinMods]
removeButton = "Usuń"
deleteFailedTitle = "Błąd podczas usuwania<br>moda {fullName}"
deleteFailedMessage = "Upewnij się, że plik nie jest używany i spróbuj ponownie."
failedToggleTitle = "Błąd podczas aktywacji<br>jednego lub więcej modów"
okButton = "Okej"

[js.settings.serverListing]
mainServer = "Główny Serwer"

[js.settings.java]
selectedJava = "Wybrano: Java {version} ({vendor})"
invalidSelection = "Nieprawidłowy wybór"
requiresJava = "Wymagana Java {major} x64."
availableOptions = "Available Options for Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Wersja stabilna"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "Dostępna nowa wersja"
newPreReleaseTitle = "New Pre-release Available"
downloadingButton = "Pobieranie.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "Korzystasz już z najnowszej wersji"
checkForUpdatesButton = "Sprawdź aktualizacje"
checkingForUpdatesButton = "Sprawdzanie aktualizacji.."

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Nie udało się odświeżyć logowania"
failedMessage = "Nie udało nam się odświeżyć logowania dla <strong>{account}</strong>. Wybierz inne konto lub zaloguj się ponownie."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "Login"
selectAnotherAccountButton = "Wybierz inne konto"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Sprawdzam dostępność aktualizacji..."
installNowButton = "Zainstaluj teraz"
checkForUpdatesButton = "Sprawdź aktualizacje"
